variables:
  data_local: ???
  data_remote:  # If blank, files must be present in data_local
  max_seq_len: ???
  global_seed: ???
  train_num_workers: ???
  eval_num_workers: ???
  embedding_momentum: ???
  embedding_nesterov: ???
  embedding_norm_factor: ???
  embedding_dual: ???
  embedding_backend: ???
  unembedding_norm_factor: ???
  unembedding_backend: ???
  dual_norm_scaling: ???
  eps_base: ???
  init_std_base: ???
  emb_init_std_base: ???
  lr_base: ???
  embedding_lr_base: ???
  # mup_config: 
    # d_model_base: ???
    # n_heads_base: ???
    # d_heads_base: ${eval:'${.d_model_base} / ${.n_heads_base}'}
    # d_heads: ${eval:'${model.d_model} / ${model.n_heads}'}
    # d_model_ratio: ${eval:'${model.d_model} / ${.d_model_base}'} 
    # init_std_base: ???
    # param_groups: # NB: add/remove `gate_proj` entry depending on ffn_type!
    #   - param_str_match: attn.Wqkv.weight
    #     lr: ${eval:'${optimizer.lr} / ${variables.mup_config.d_model_ratio}'}
    #     eps: ${eval:'${variables.mup_config.eps_base} / ${variables.mup_config.d_model_ratio}'}
    #     weight_decay: ${eval:'${optimizer.weight_decay} * ${variables.mup_config.d_model_ratio} if "decoupled" not in "${optimizer.name}" else ${optimizer.weight_decay}'}
    #   - param_str_match: attn.out_proj.weight
    #     lr: ${eval:'${optimizer.lr} / ${variables.mup_config.d_model_ratio}'}
    #     eps: ${eval:'${variables.mup_config.eps_base} / ${variables.mup_config.d_model_ratio}'}
    #     weight_decay: ${eval:'${optimizer.weight_decay} * ${variables.mup_config.d_model_ratio} if "decoupled" not in "${optimizer.name}" else ${optimizer.weight_decay}'}
    #   - param_str_match: ffn.up_proj.weight
    #     lr: ${eval:'${optimizer.lr} / ${variables.mup_config.d_model_ratio}'}
    #     eps: ${eval:'${variables.mup_config.eps_base} / ${variables.mup_config.d_model_ratio}'}
    #     weight_decay: ${eval:'${optimizer.weight_decay} * ${variables.mup_config.d_model_ratio} if "decoupled" not in "${optimizer.name}" else ${optimizer.weight_decay}'}
    #   - param_str_match: ffn.down_proj.weight
    #     lr: ${eval:'${optimizer.lr} / ${variables.mup_config.d_model_ratio}'}
    #     eps: ${eval:'${variables.mup_config.eps_base} / ${variables.mup_config.d_model_ratio}'}
    #     weight_decay: ${eval:'${optimizer.weight_decay} * ${variables.mup_config.d_model_ratio} if "decoupled" not in "${optimizer.name}" else ${optimizer.weight_decay}'}
    #   - param_str_match: ffn.gate_proj.weight
    #     lr: ${eval:'${optimizer.lr} / ${variables.mup_config.d_model_ratio}'}
    #     eps: ${eval:'${variables.mup_config.eps_base} / ${variables.mup_config.d_model_ratio}'}
    #     weight_decay: ${eval:'${optimizer.weight_decay} * ${variables.mup_config.d_model_ratio} if "decoupled" not in "${optimizer.name}" else ${optimizer.weight_decay}'}

  # Run Name
  run_name:  # If left blank, will be read from env var $RUN_NAME

max_seq_len: ${variables.max_seq_len}
run_name: ${variables.run_name}

# Model
model:
  name: mpt_causal_lm
  init_device: meta
  d_model: ???
  n_heads: ???
  n_layers: ???
  expansion_ratio: ???
  max_seq_len: ${variables.max_seq_len}
  learned_pos_emb: false
  vocab_size: ???
  resid_pdrop: 0.0
  emb_pdrop: 0.0
  embedding_fraction: 1.0
  tie_word_embeddings: false
  no_bias: true
  norm_type: ???
  norm_eps: 1e-15
  norm_weight: false # only valid for norm_type={rmsnorm, low_precision_rmsnorm}
  logit_scale: 1.0 # ${eval:'(256 / ${model.d_model})**0.5'}
  fc_type: torch
  ffn_config:
    ffn_type: mptmlp
    ffn_act_fn: 
      name: relu
  attn_config:
    attn_type: multihead_attention
    attn_impl: flash
    attn_pdrop: 0.0
    n_heads: ${model.n_heads}
    softmax_scale: ${eval:'1 / (${model.d_model} / ${model.n_heads})**0.5'}
    qk_ln: false
    qk_gn: false
    fused_qkv: true
    clip_qkv: null
    attn_uses_sequence_id: false
    sliding_window_size: -1
    alibi: false
    rope: true
    rope_theta: 500000
    rope_impl: hf
    rope_hf_config:
      type: no_scaling
      factor: 1.0
  init_config:
    name: baseline_
    init_std: ${eval:'${variables.init_std_base} / (${model.d_model})**0.5'}
    # d_model: null # in theory shouldn't be used, pass here as a check
    init_div_is_residual: True # True: 1 / math.sqrt(2 * cfg.n_layers)
    emb_init_std: ${eval:'${variables.emb_init_std_base} / (256)**0.5'} # ${eval:'1e4 * (${model.d_model}/${model.vocab_size})**0.5 / ((${model.d_model})**0.5+(${model.vocab_size})**0.5)'}
    unemb_init_std: -999 # patched in source to: ${eval:'(${model.vocab_size}/${model.d_model})**0.5 / ((${model.d_model})**0.5+(${model.vocab_size})**0.5)'}

  # init_config: # init v3
  #   name: baseline_
  #   init_std: ${eval:'1 / ${model.d_model}**0.5'}
  #   # d_model: null # in theory shouldn't be used, pass here as a check
  #   init_div_is_residual: True # True: 1 / math.sqrt(2 * cfg.n_layers)
  #   emb_init_std: ${eval:'1e4 * (${model.d_model}/${model.vocab_size})**0.5 / ((${model.d_model})**0.5+(${model.vocab_size})**0.5)'}
  #   unemb_init_std: -999 # patched in source to: ${eval:'(${model.vocab_size}/${model.d_model})**0.5 / ((${model.d_model})**0.5+(${model.vocab_size})**0.5)'}
      
  # init_config: # init v2
  #   name: baseline_
  #   init_std: 0.0625
  #   # d_model: null # in theory shouldn't be used, pass here as a check
  #   init_div_is_residual: True # True: 1 / math.sqrt(2 * cfg.n_layers)
  #   emb_init_std: ${eval:'(${model.d_model}/${model.vocab_size})**0.5 / ((${model.d_model})**0.5+(${model.vocab_size})**0.5)'}
  #   unemb_init_std: ${eval:'(${model.d_model}) / ((${model.d_model})**0.5+(${model.vocab_size})**0.5)'}
  
  # init_config: # init v1
  #   name: baseline_
  #   init_std: 0.0625
  #   # d_model: null # in theory shouldn't be used, pass here as a check
  #   init_div_is_residual: True # True: 1 / math.sqrt(2 * cfg.n_layers)
  #   emb_init_std: ${eval:'(${model.d_model}/${model.vocab_size})**0.5 / ((${model.d_model})**0.5+(${model.vocab_size})**0.5)'}
  #   unemb_init_std: ${eval:'((${model.d_model})**0.5) / ((${model.d_model})**0.5+(${model.vocab_size})**0.5)'}
  
  # init_config: # init v0
  #   name: xavier_normal_
  #   init_gain: ${eval:'(${model.d_model})**0.5 / 16'}
  #   # d_model: null # in theory shouldn't be used, pass here as a check
  #   init_div_is_residual: True # True: 1 / math.sqrt(2 * cfg.n_layers)
  #   emb_init_std: ${eval:'(${model.d_model}/${model.vocab_size})**0.5 / ((${model.d_model})**0.5+(${model.vocab_size})**0.5)'}
  #   unemb_init_std: ${eval:'((${model.vocab_size})**0.5 / 16) / ((${model.d_model})**0.5+(${model.vocab_size})**0.5)'}

# Tokenizer
tokenizer:
  name: ???
  kwargs:
    model_max_length: ${variables.max_seq_len}
    use_fast: False

# Dataloaders
train_loader:
  name: text
  dataset:
    local:
    remote:
    split: train
    shuffle: true
    max_seq_len: ${variables.max_seq_len}
    shuffle_seed: ${variables.global_seed}
    epoch_size: ${eval:'1073741824 / ${variables.max_seq_len}'}
    streams:
      eng-fast:
        local:  "${variables.data_local}/eng-fast"
        proportion: 1 # 0.34862683488597324
      # fao:
      #   local:  "${variables.data_local}/fao"
      #   proportion: 0.5 # 4.082718707022429e-06
  drop_last: true
  num_workers: ${variables.train_num_workers}
  prefetch_factor: 2

eval_loader:
  - name: text
    label: eng-fast
    dataset:
      local:
      remote:
      split: val
      shuffle: false
      max_seq_len: ${variables.max_seq_len}
      shuffle_seed: ${variables.global_seed}
      epoch_size: null # will be set to the sum of streams
      streams:
        eng-fast:
          local:  "${variables.data_local}/eng-fast"
          repeat: 1  
    drop_last: false
    num_workers: ${variables.eval_num_workers}
    prefetch_factor: 2
  # - name: text
  #   label: fao
  #   dataset:
  #     local:
  #     remote:
  #     split: val
  #     shuffle: false
  #     max_seq_len: ${variables.max_seq_len}
  #     shuffle_seed: ${variables.global_seed}
  #     epoch_size: null # will be set to the sum of streams
  #     streams:
  #       fao:
  #         local:  "${variables.data_local}/fao"
  #         repeat: 1      
  #   drop_last: false
  #   num_workers: ${variables.eval_num_workers}
  #   prefetch_factor: 2

# Optimization
scheduler:
  name: ???
  t_warmup: ???
  t_constant: ???
  t_decay: ???
  alpha_f: ???

optimizer:
  name: ???
  lr: ${eval:'${variables.lr_base}'} #  * (${model.d_model} / 256)
  momentum: ???
  nesterov: ???
  dual_norm_scaling: ${variables.dual_norm_scaling}
  eps: ${variables.eps_base}
  norm_factor: 'linear'
  backend: 'newtonschulz5'
  param_groups: # NB: add/remove `gate_proj` entry depending on ffn_type!
    - param_str_match: wte.weight
      lr: ${eval:'${variables.embedding_lr_base} / (256)**0.5'} # ${eval:'${variables.embedding_lr_base} / 256 * ${model.d_model}**0.5'}   ////////   ${eval:'${variables.embedding_lr_base} / (256)**0.5'}
      momentum: ${variables.embedding_momentum}
      nesterov: ${variables.embedding_nesterov}
      norm_factor: ${variables.embedding_norm_factor}
      backend: ${variables.embedding_backend}
      dual_norm_scaling: ${variables.embedding_dual}
    - param_str_match: lm_head.weight
      lr: ${eval:'${variables.embedding_lr_base} * 256 / (${model.d_model})**0.5'}
      momentum: ${variables.embedding_momentum}
      nesterov: ${variables.embedding_nesterov}
      norm_factor: ${variables.unembedding_norm_factor}
      backend: ${variables.unembedding_backend}
    # - param_str_match: attn.Wqkv.weight
    #   norm_factor: 'linear'
    #   backend: 'newtonschulz5'
    # - param_str_match: attn.out_proj.weight
    #   norm_factor: 'linear'
    #   backend: 'newtonschulz5'
    # - param_str_match: ffn.up_proj.weight
    #   norm_factor: 'linear'
    #   backend: 'newtonschulz5'
    # - param_str_match: ffn.down_proj.weight
    #   norm_factor: 'linear'
    #   backend: 'newtonschulz5'
    # - param_str_match: ffn.gate_proj.weight
    #   norm_factor: 'linear'
    #   backend: 'newtonschulz5'

# optimizer: # v2
#   name: ???
#   lr: ???
#   momentum: 0.95
#   nesterov: true
#   dual_norm_scaling: ${variables.dual_norm_scaling}
#   eps: ${variables.eps_base}
#   norm_factor: 'linear'
#   backend: 'newtonschulz5'
#   param_groups: # NB: add/remove `gate_proj` entry depending on ffn_type!
#     - param_str_match: wte.weight
#       lr: ${eval:'${variables.embedding_lr} * ${model.d_model} / 256'}
#       momentum: ${variables.embedding_momentum}
#       nesterov: ${variables.embedding_nesterov}
#       norm_factor: 'linear' # 'embed'
#       backend: 'newtonschulz5' # 'identity'
#       dual_norm_scaling: ${variables.embedding_dual}

# optimizer: # v1
  # name: ???
  # lr: ???
  # momentum: 0.95
  # nesterov: true
  # dual_norm_scaling: ${variables.dual_norm_scaling}
  # eps: ${variables.eps_base}
  # norm_factor: 'linear'
  # backend: 'newtonschulz5'
  # param_groups: # NB: add/remove `gate_proj` entry depending on ffn_type!
  #   - param_str_match: wte.weight
  #     momentum: ${variables.embedding_momentum}
  #     nesterov: ${variables.embedding_nesterov}
  #     dual_norm_scaling: ${variables.embedding_dual}

# optimizer: # opt v0
#   name: ???
#   lr: ${eval:'${variables.lr} * (${model.d_model} / 256)**0.5'}
#   momentum: 0.95
#   nesterov: true
#   dual_norm_scaling: ${variables.dual_norm_scaling}
#   eps: ${variables.eps_base}
#   norm_factor: 'none'
#   backend: 'newtonschulz5'
#   param_groups: # NB: add/remove `gate_proj` entry depending on ffn_type!
#     - param_str_match: wte.weight
#       lr: ${variables.embedding_lr}
#       momentum: ${variables.embedding_momentum}
#       nesterov: ${variables.embedding_nesterov}
#       norm_factor: 'none' # 'embed'
#       backend: 'newtonschulz5' # 'identity'
#       dual_norm_scaling: ${variables.embedding_dual}

# optimizer:
#   name: ???
#   lr: ???
#   betas: ???
#   weight_decay: ???
#   eps: ${variables.mup_config.eps_base}
#   # param_groups: ${variables.mup_config.param_groups}

# algorithms:
#   gradient_clipping:
#     clipping_type: norm
#     clipping_threshold: 1.0

max_duration: ???
eval_interval: ???
eval_first: false
eval_subset_num_batches: -1
global_train_batch_size: ???

# System
seed: ${variables.global_seed}
device_eval_batch_size: ???
device_train_microbatch_size: ???
# device_train_microbatch_size: auto
precision: ???
accumulate_train_batch_on_tokens: ??? # default: True

# FSDP
fsdp_config: null
  # use_orig_params: true
  # sharding_strategy: ???
  # mixed_precision: PURE
  # activation_checkpointing: false
  # activation_checkpointing_reentrant: false
  # activation_cpu_offload: false
  # limit_all_gathers: true
tp_config: null

# Logging
progress_bar: false
log_to_console: true
console_log_interval: 1ba

callbacks:
  # speed_monitor:
  #   window_size: 10
  optimizer_monitor:
    batch_log_interval: ???
  mup_monitor:
    batch_log_interval: ???
  lr_monitor: {}
  # memory_monitor: {}
  # runtime_estimator: {}

loggers:
  mlflow:
    tracking_uri: ???
    experiment_name: ???
    run_name: ${run_name}
    resume: ???
    ignore_hyperparameters: []
  tensorboard:
    log_dir: ???
    flush_interval: 100

# Checkpoint to local filesystem or remote object store
save_interval: ???
save_overwrite: ???
save_num_checkpoints_to_keep: ???
save_folder: ???
save_weights_only: false

# Load from local filesystem or remote object store
load_path: ???
